### ISSUE TITLE
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode'

### ISSUE THREAD

**Issue by superman566** [hyperledger-labs/minifabric#214] opened 2021-05-26 03:13 UTC
Installed docker dashboard in my Mac OS and run the default `minifab up`. then there will be an error in the step named # Run the chaincode install script on cli container ***********

```
.......
# Run the chaincode install script on cli container ***********
  non-zero return code
  go: downloading github.com/hyperledger/fabric v1.4.1
  go: finding module for package google.golang.org/grpc/stats
  go: finding module for package github.com/op/go-logging
  go: downloading github.com/golang/protobuf v1.3.1
  go: finding module for package golang.org/x/net/context
  go: finding module for package google.golang.org/grpc/keepalive
  go: finding module for package github.com/spf13/viper
  go: finding module for package google.golang.org/grpc
  go: finding module for package github.com/pkg/errors
  go: finding module for package google.golang.org/grpc/peer
  go: finding module for package go.uber.org/zap/zapcore
  go: downloading github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
  go: downloading github.com/spf13/viper v1.7.1
  go: downloading github.com/pkg/errors v0.9.1
  go: downloading google.golang.org/grpc v1.38.0
  go: downloading golang.org/x/net v0.0.0-20210525063256-abc453219eb5
  go: downloading go.uber.org/zap v1.17.0
  go: finding module for package github.com/miekg/pkcs11
  go: finding module for package github.com/grpc-ecosystem/go-grpc-middleware
  go: finding module for package google.golang.org/grpc/grpclog
  go: finding module for package go.uber.org/zap/buffer
  go: downloading github.com/miekg/pkcs11 v1.0.3
  go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
  go: finding module for package go.uber.org/zap/zapgrpc
  go: finding module for package github.com/sykesm/zap-logfmt
  go: finding module for package go.uber.org/zap
  go: finding module for package golang.org/x/crypto/sha3
  go: finding module for package google.golang.org/grpc/credentials
  go: finding module for package gopkg.in/yaml.v2
  go: finding module for package github.com/hyperledger/fabric-amcl/amcl
  go: finding module for package github.com/hyperledger/fabric-amcl/amcl/FP256BN
  go: finding module for package github.com/fsouza/go-dockerclient
  go: downloading github.com/sykesm/zap-logfmt v0.0.4
  go: downloading golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
  go: downloading github.com/hyperledger/fabric-amcl v0.0.0-20210319225857-000ace5745f9
  go: downloading github.com/fsouza/go-dockerclient v1.7.2
  go: downloading gopkg.in/yaml.v2 v2.4.0
  go: found github.com/op/go-logging in github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
  go: found github.com/pkg/errors in github.com/pkg/errors v0.9.1
  go: found github.com/spf13/viper in github.com/spf13/viper v1.7.1
  go: found google.golang.org/grpc in google.golang.org/grpc v1.38.0
  go: found golang.org/x/net/context in golang.org/x/net v0.0.0-20210525063256-abc453219eb5
  go: found github.com/grpc-ecosystem/go-grpc-middleware in github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
  go: found github.com/miekg/pkcs11 in github.com/miekg/pkcs11 v1.0.3
  go: found go.uber.org/zap/zapcore in go.uber.org/zap v1.17.0
  go: found golang.org/x/crypto/sha3 in golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
  go: found github.com/sykesm/zap-logfmt in github.com/sykesm/zap-logfmt v0.0.4
  go: found gopkg.in/yaml.v2 in gopkg.in/yaml.v2 v2.4.0
  go: found github.com/fsouza/go-dockerclient in github.com/fsouza/go-dockerclient v1.7.2
  go: found github.com/hyperledger/fabric-amcl/amcl in github.com/hyperledger/fabric-amcl v0.0.0-20210319225857-000ace5745f9
  go: downloading github.com/golang/protobuf v1.4.2
  go: downloading google.golang.org/genproto v0.0.0-20200526211855-cb27e3aa2013
  go: downloading golang.org/x/sys v0.0.0-20210423082822-04245dca01da
  go: downloading github.com/mitchellh/mapstructure v1.1.2
  go: downloading github.com/spf13/cast v1.3.0
  go: downloading github.com/spf13/jwalterweatherman v1.0.0
  go: downloading golang.org/x/text v0.3.6
  go: downloading github.com/spf13/afero v1.1.2
  go: downloading google.golang.org/protobuf v1.25.0
  go: downloading github.com/spf13/pflag v1.0.3
  go: downloading github.com/pelletier/go-toml v1.2.0
  go: downloading gopkg.in/ini.v1 v1.51.0
  go: downloading github.com/hashicorp/hcl v1.0.0
  go: downloading github.com/subosito/gotenv v1.2.0
  go: downloading github.com/fsnotify/fsnotify v1.4.7
  go: downloading github.com/magiconair/properties v1.8.1
  go: downloading go.uber.org/multierr v1.6.0
  go: downloading github.com/docker/docker v20.10.3-0.20210216175712-646072ed6524+incompatible
  go: downloading github.com/docker/go-units v0.4.0
  go: downloading go.uber.org/atomic v1.7.0
  go: downloading github.com/Microsoft/go-winio v0.4.16
  go: downloading github.com/opencontainers/image-spec v1.0.1
  go: downloading github.com/sirupsen/logrus v1.7.0
  go: downloading github.com/morikuni/aec v1.0.0
  go: downloading github.com/moby/term v0.0.0-20201216013528-df9cb8a40635
  go: downloading github.com/containerd/continuity v0.0.0-20210208174643-50096c924a4e
  go: downloading github.com/containerd/containerd v1.4.3
  go: downloading github.com/moby/sys/mount v0.2.0
  go: downloading github.com/gogo/protobuf v1.3.2
  go: downloading github.com/docker/go-connections v0.4.0
  go: downloading github.com/Microsoft/hcsshim v0.8.14
  go: downloading github.com/opencontainers/runc v0.1.1
  go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
  go: downloading github.com/moby/sys/mountinfo v0.4.0
  go: downloading github.com/opencontainers/go-digest v1.0.0
  go: downloading golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9
  go: downloading go.opencensus.io v0.22.0
  go: downloading github.com/containerd/cgroups v0.0.0-20200531161412-0dbf7f05ba59
  go: downloading github.com/hashicorp/golang-lru v0.5.1
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: Get "http://unix.sock/images/dev-peer1.org0.example.com-simple_1.0-50262e39389596bf54c4e3637963504484d256280792a223ad66a37f9b474b56-c175ed0705516940a1c3157903cf3dd919a45187c35bc9ad15c0042408f5d2ed/json": dial unix /host/var/run/docker.sock: connect: no such file or directory

# STATS *******************************************************
minifab: ok=353	failed=1	

real	4m0.800s
user	1m29.241s
sys	0m30.718s
```

**Comment by superman566** [comment] 2021-05-26 03:14
my docker version is : 
![image](https://user-images.githubusercontent.com/8649164/119597385-e93d4d00-bdae-11eb-9a87-a8b3628248cb.png)

**Comment by superman566** [comment] 2021-05-26 03:16
it is similar with #87 , but looks like it did not get fixed.

**Comment by litong01** [comment] 2021-05-26 12:47
@superman566 the problem is that mac docker has this Use gRPC FUSE for file sharing option. If you disable that from general setting page, you should be ok. This has come up many times, there were more than one duplicate on this. Please confirm that this issue is due to this, once verified , please close this one. Thanks.

**Comment by superman566** [comment] 2021-05-26 14:01
Thanks, @litong01 , it got Verified. It is working fine after disable gRPC FUSE option in Mac docker dashboard. If it is a common issue, whether it can be mentioned in README.md so new users will know how to figure it out by themselves.

**Closed** 2021-05-26 14:01 UTC

**Comment by litong01** [comment] 2021-05-26 14:05
@superman566 this only happens on mac. other docker env has no such issue. I would not recommend add this to the main README.md file. However, you are very welcome to create a PR (for the benefit of others). In the PR you can add small section to the docs/README.md file and highlight this configuration option and what issue may rise due to this option.

**Comment by superman566** [comment] 2021-05-26 14:27
I think it is a good idea to keep it in a separate file, and I am glad to create a PR for this.

**Comment by litong01** [comment] 2021-05-26 14:29
@aguel @superman566 I think in a separate file is a good idea as well. Please create a new doc and name it so that user wont mistaken it as the issues cannot be resolves or due to minifabric problems. For example, it wont run on machine with M1 chip, but that is not due to minifabric. Thanks for your contributions.

**Comment by aguel** [comment] 2021-05-26 14:37
@litong01 @superman566 Even better, make it concise and straight forward (rather than lengthy and difficult to follow/read) and simply add reference to the relevant issue number/numbers (if any) so others can simply click and view the whole issue and get more detailed information directly from the referenced ticket. Just a suggestion.

**Comment by superman566** [comment] 2021-05-26 14:41
Thanks, @aguel . It is a good point.

**Comment by aguel** [comment] 2021-05-26 14:52
@litong01 @superman566 Maybe something like this (feel free to suggest something else)

*************

**ISSUE**: _Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode'_
**ENVIRONMENT**: _Apple Silicon M1 / MacOS Big Sur  10.3.1  / Docker 3.x.x_
**SOLUTION**:  
- _Open Preferences_
- _Click Experimental Features_
- _disable Use gRPC FUSE for file sharing_
- _Apply / Restart_

**Related issue(s)**: #214 #87

*************

**Comment by litong01** [comment] 2021-05-26 14:58
@aguel looks good to me.

**Comment by aguel** [comment] 2021-05-26 15:27
@superman566 let me know if you are pushing the PR? Otherwise I can do the same. Cheers.

**Comment by superman566** [comment] 2021-05-26 16:09
A PR is created: https://github.com/hyperledger-labs/minifabric/pull/216. 

@litong01 and @aguel , do we have some rules for First-time contributors need to follow?
