### ISSUE TITLE
running minicab up generated error

### ISSUE THREAD

**Issue by webzest** [hyperledger-labs/minifabric#305] opened 2021-11-23 19:33 UTC
OS:  MAC Big Sur
johnny@JohnnyMBP hyperLedgerMiniFab % docker version
Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

johnny@JohnnyMBP hyperLedgerMiniFab % ./minifab up  
Using default spec file
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.2
    WORKING_DIRECTORY: /Users/johnny/hyperLedgerMiniFab

# Run the chaincode install script on cli container ***********
  non-zero return code
  go: downloading github.com/hyperledger/fabric v1.4.1
  go: downloading github.com/golang/protobuf v1.3.3
  go: downloading github.com/pkg/errors v0.9.1
  go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
  go: downloading github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
  go: downloading github.com/spf13/viper v1.7.1
  go: downloading google.golang.org/grpc v1.31.1
  go: downloading go.uber.org/zap v1.15.0
  go: downloading github.com/spf13/jwalterweatherman v1.0.0
  go: downloading gopkg.in/ini.v1 v1.51.0
  go: downloading github.com/spf13/cast v1.3.0
  go: downloading gopkg.in/yaml.v2 v2.3.0
  go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
  go: downloading go.uber.org/atomic v1.6.0
  go: downloading go.uber.org/multierr v1.5.0
  go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.2.1
  go: downloading github.com/spf13/afero v1.1.2
  go: downloading github.com/fsnotify/fsnotify v1.4.7
  go: downloading github.com/pelletier/go-toml v1.2.0
  go: downloading github.com/magiconair/properties v1.8.1
  go: downloading github.com/subosito/gotenv v1.2.0
  go: downloading github.com/mitchellh/mapstructure v1.1.2
  go: downloading github.com/hashicorp/hcl v1.0.0
  go: downloading google.golang.org/genproto v0.0.0-20200423170343-7949de9c1215
  go: finding module for package github.com/miekg/pkcs11
  go: downloading golang.org/x/sys v0.0.0-20200420163511-1957bb5e6d1f
  go: downloading github.com/spf13/pflag v1.0.3
  go: downloading github.com/sykesm/zap-logfmt v0.0.3
  go: downloading golang.org/x/text v0.3.2
  go: downloading github.com/miekg/pkcs11 v1.0.3
  go: downloading github.com/fsouza/go-dockerclient v1.6.5
  go: downloading github.com/hyperledger/fabric-amcl v0.0.0-20200424173818-327c9e2cf77a
  go: downloading github.com/docker/docker v1.4.2-0.20191101170500-ac7306503d23
  go: downloading github.com/Microsoft/go-winio v0.4.15-0.20200113171025-3fe6c5262873
  go: downloading github.com/docker/go-units v0.4.0
  go: downloading github.com/opencontainers/image-spec v1.0.1
  go: downloading github.com/morikuni/aec v1.0.0
  go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
  go: downloading github.com/opencontainers/runc v0.1.1
  go: downloading github.com/containerd/continuity v0.0.0-20200228182428-0f16d7a0959c
  go: downloading github.com/Microsoft/hcsshim v0.8.7
  go: downloading github.com/sirupsen/logrus v1.4.2
  go: downloading github.com/docker/go-connections v0.4.0
  go: downloading github.com/gogo/protobuf v1.3.1
  go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
  go: downloading github.com/docker/distribution v2.7.1+incompatible
  go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
  go: downloading github.com/containerd/containerd v1.3.0
  go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
  go: found github.com/miekg/pkcs11 in github.com/miekg/pkcs11 v1.0.3
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: Get "http://unix.sock/images/dev-peer1.org0.example.com-simple_1.0-bb0642f7184041106dc3c495de384d3f4788ada0639be92b561461b35edffb67-7821bed4419d0df065d2627a604d7dae23d96ef012bff2b4115469327f0b87aa/json": dial unix /host/var/run/docker.sock: connect: no such file or directory

# STATS *******************************************************
minifab: ok=347	failed=1	

real	2m48.575s
user	1m52.374s
sys	0m37.481s

**Comment by litong01** [comment] 2021-11-24 00:54
It will be nice to have the commands that you were running to reproduce the error. Also describe if you use your own spec file or the default one. Without these information, it is a bit hard to help.

**Comment by webzest** [comment] 2021-11-24 02:23
Hi Tong,

I started with the link from GIT:
```
mkdir -p ~/mywork && cd ~/mywork && curl -o minifab -sL https://tinyurl.com/yxa2q6yr && chmod +x minifab`
Then, I launch minifab: `./minifab up`

![image](https://user-images.githubusercontent.com/6105504/143159662-829cb84c-d096-4c17-92e0-4ffadc91d59e.png)

Then, it ran everything until this point and errored out:

# Run the chaincode install script on cli container ***********
  non-zero return code
  go: downloading github.com/hyperledger/fabric v1.4.1
  go: downloading github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
  go: downloading github.com/pkg/errors v0.9.1
  go: downloading google.golang.org/grpc v1.31.1
  go: downloading go.uber.org/zap v1.15.0
  go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
  go: downloading github.com/spf13/viper v1.7.1
  go: downloading github.com/sykesm/zap-logfmt v0.0.3
  go: downloading github.com/golang/protobuf v1.3.3
  go: downloading go.uber.org/multierr v1.5.0
  go: downloading github.com/subosito/gotenv v1.2.0
  go: downloading github.com/pelletier/go-toml v1.2.0
  go: downloading github.com/hyperledger/fabric-amcl v0.0.0-20200424173818-327c9e2cf77a
  go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.2.1
  go: downloading go.uber.org/atomic v1.6.0
  go: downloading github.com/spf13/pflag v1.0.3
  go: downloading github.com/hashicorp/hcl v1.0.0
  go: downloading github.com/mitchellh/mapstructure v1.1.2
  go: downloading github.com/spf13/cast v1.3.0
  go: downloading gopkg.in/ini.v1 v1.51.0
  go: finding module for package github.com/miekg/pkcs11
  go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
  go: downloading github.com/spf13/afero v1.1.2
  go: downloading github.com/fsouza/go-dockerclient v1.6.5
  go: downloading github.com/fsnotify/fsnotify v1.4.7
  go: downloading golang.org/x/sys v0.0.0-20200420163511-1957bb5e6d1f
  go: downloading golang.org/x/text v0.3.2
  go: downloading github.com/spf13/jwalterweatherman v1.0.0
  go: downloading google.golang.org/genproto v0.0.0-20200423170343-7949de9c1215
  go: downloading github.com/magiconair/properties v1.8.1
  go: downloading github.com/Microsoft/go-winio v0.4.15-0.20200113171025-3fe6c5262873
  go: downloading github.com/miekg/pkcs11 v1.0.3
  go: downloading github.com/docker/docker v1.4.2-0.20191101170500-ac7306503d23
  go: downloading gopkg.in/yaml.v2 v2.3.0
  go: downloading github.com/docker/go-units v0.4.0
  go: downloading github.com/sirupsen/logrus v1.4.2
  go: downloading github.com/docker/go-connections v0.4.0
  go: downloading github.com/containerd/continuity v0.0.0-20200228182428-0f16d7a0959c
  go: downloading github.com/gogo/protobuf v1.3.1
  go: downloading github.com/opencontainers/runc v0.1.1
  go: downloading github.com/opencontainers/image-spec v1.0.1
  go: downloading github.com/docker/distribution v2.7.1+incompatible
  go: downloading github.com/morikuni/aec v1.0.0
  go: downloading github.com/Microsoft/hcsshim v0.8.7
  go: downloading github.com/containerd/containerd v1.3.0
  go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
  go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
  go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
  go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
  go: found github.com/miekg/pkcs11 in github.com/miekg/pkcs11 v1.0.3
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: Get "http://unix.sock/images/dev-peer1.org0.example.com-simple_1.0-bb0642f7184041106dc3c495de384d3f4788ada0639be92b561461b35edffb67-7821bed4419d0df065d2627a604d7dae23d96ef012bff2b4115469327f0b87aa/json": dial unix /host/var/run/docker.sock: connect: no such file or directory

# STATS *******************************************************
minifab: ok=347	failed=1	

real	3m1.090s
user	2m0.944s
sys	0m40.378s
johnny@JohnnyMBP mywork % 
```

**Comment by litong01** [comment] 2021-11-24 15:51
the sample chaincode has been updated recently. I wonder if you are having the older minifab docker container. Can you run `./minifab up` and then `./minifab cleanup`, `./minifab up`? also if you are on mac M1 chip, it is known that fabric wont work on it.

**Comment by webzest** [comment] 2021-11-25 13:26
Could this be related?

The 2.3 release was an interim/development release. 2.2 being the LTS. There wasn't a docker image for farbic-javaenv:2.3 released.  The quick way around this is to pul down the fabric-javaenv:2.2 and retag it as 2.3

**Comment by litong01** [comment] 2021-11-29 14:36
@webzest So this is running on Mac using docker desktop, is that correct? If so, please search closed mac related issues against minifabric, I think this is due to an enabled (by default) experimental feature on docker desktop only affect mac users. Please following this link https://github.com/hyperledger-labs/minifabric/issues?q=is%3Aissue+is%3Aclosed+FUSE and I think this one https://github.com/hyperledger-labs/minifabric/issues/214 also provided solution.

**Comment by litong01** [comment] 2021-12-10 18:03
Please close this issue if the solution worked for you.

**Closed** 2021-12-21 12:23 UTC
